/** This is an autogenerated file, please do not change this file directly. */
declare namespace TransitionerModuleScssModule {
    export interface ITransitionerModuleScss {
        fadeIn: string;
        fadeOut: string;
    }
}

declare const TransitionerModuleScssModule: TransitionerModuleScssModule.ITransitionerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TransitionerModuleScssModule.ITransitionerModuleScss;
};

export = TransitionerModuleScssModule;
