/** This is an autogenerated file, please do not change this file directly. */
declare namespace BasicInfoModuleScssModule {
    export interface IBasicInfoModuleScss {
        basicInfo: string;
        connector: string;
        dateInfo: string;
        dateLabel: string;
        dateValue: string;
        end: string;
        fadeIn: string;
        info: string;
        label: string;
        middle: string;
        start: string;
        value: string;
    }
}

declare const BasicInfoModuleScssModule: BasicInfoModuleScssModule.IBasicInfoModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BasicInfoModuleScssModule.IBasicInfoModuleScss;
};

export = BasicInfoModuleScssModule;
