/** This is an autogenerated file, please do not change this file directly. */
declare namespace GrowthCurveModuleScssModule {
    export interface IGrowthCurveModuleScss {
        end: string;
        fadeIn: string;
        growthCurveContainer: string;
        middle: string;
        start: string;
    }
}

declare const GrowthCurveModuleScssModule: GrowthCurveModuleScssModule.IGrowthCurveModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GrowthCurveModuleScssModule.IGrowthCurveModuleScss;
};

export = GrowthCurveModuleScssModule;
