/** This is an autogenerated file, please do not change this file directly. */
declare namespace BasicInfoPanelModuleScssModule {
    export interface IBasicInfoPanelModuleScss {
        connector: string;
        dateInfo: string;
        dateLabel: string;
        dateValue: string;
        end: string;
        hoverInfo: string;
        info: string;
        infoContainer: string;
        internalContainer: string;
        label: string;
        middle: string;
        start: string;
        title: string;
        transitioner: string;
        value: string;
    }
}

declare const BasicInfoPanelModuleScssModule: BasicInfoPanelModuleScssModule.IBasicInfoPanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BasicInfoPanelModuleScssModule.IBasicInfoPanelModuleScss;
};

export = BasicInfoPanelModuleScssModule;
