/** This is an autogenerated file, please do not change this file directly. */
declare namespace DeepDivePanelModuleScssModule {
    export interface IDeepDivePanelModuleScss {
        deepDiveContainer: string;
        end: string;
        internalContainer: string;
        middle: string;
        start: string;
        title: string;
    }
}

declare const DeepDivePanelModuleScssModule: DeepDivePanelModuleScssModule.IDeepDivePanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DeepDivePanelModuleScssModule.IDeepDivePanelModuleScss;
};

export = DeepDivePanelModuleScssModule;
