/** This is an autogenerated file, please do not change this file directly. */
declare namespace PanelsModuleScssModule {
    export interface IPanelsModuleScss {
        panelContainer: string;
    }
}

declare const PanelsModuleScssModule: PanelsModuleScssModule.IPanelsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PanelsModuleScssModule.IPanelsModuleScss;
};

export = PanelsModuleScssModule;
