/** This is an autogenerated file, please do not change this file directly. */
declare namespace StatsPanelModuleScssModule {
    export interface IStatsPanelModuleScss {
        caseBreakdownContainer: string;
        end: string;
        filterContainer: string;
        highlight: string;
        isOpen: string;
        middle: string;
        singleBreakdown: string;
        start: string;
        statsPanelContainer: string;
        text: string;
        titleBackButton: string;
        titleContainer: string;
        titleText: string;
        totalCasesContainer: string;
    }
}

declare const StatsPanelModuleScssModule: StatsPanelModuleScssModule.IStatsPanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StatsPanelModuleScssModule.IStatsPanelModuleScss;
};

export = StatsPanelModuleScssModule;
