/** This is an autogenerated file, please do not change this file directly. */
declare namespace InformationModuleScssModule {
    export interface IInformationModuleScss {
        contact: string;
        data: string;
        infoIcon: string;
        legal: string;
    }
}

declare const InformationModuleScssModule: InformationModuleScssModule.IInformationModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: InformationModuleScssModule.IInformationModuleScss;
};

export = InformationModuleScssModule;
