/** This is an autogenerated file, please do not change this file directly. */
declare namespace TimeseriesModuleScssModule {
    export interface ITimeseriesModuleScss {
        activeCases: string;
        cases: string;
        deaths: string;
        recovered: string;
        svgContainer: string;
    }
}

declare const TimeseriesModuleScssModule: TimeseriesModuleScssModule.ITimeseriesModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TimeseriesModuleScssModule.ITimeseriesModuleScss;
};

export = TimeseriesModuleScssModule;
