/** This is an autogenerated file, please do not change this file directly. */
declare namespace UsMapModuleScssModule {
    export interface IUsMapModuleScss {
        lessThan10: string;
        lessThan100: string;
        lessThan1000: string;
        lessThan500: string;
        lessThan5000: string;
        moreThan5000: string;
        state: string;
        stateNoData: string;
        svgMap: string;
    }
}

declare const UsMapModuleScssModule: UsMapModuleScssModule.IUsMapModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: UsMapModuleScssModule.IUsMapModuleScss;
};

export = UsMapModuleScssModule;
