# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    setup:
        docker:
            - image: circleci/node:13.12.0
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    build:
        docker:
            - image: circleci/node:13.12.0
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - run:
                name: Build
                command: NODE_ENV=production yarn build
    lint:
        docker:
            - image: circleci/node:13.12.0
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - run:
                name: Build
                command: NODE_ENV=production yarn build
            - run:
                name: Lint
                command: NODE_ENV=development yarn lint
    clean-lock:
        docker:
            - image: circleci/node:13.12.0
        steps:
            - checkout
            - run:
                name: Clean yarn.lock
                command: NODE_ENV=development node ./scripts/cleanLock.js
    deploy:
        docker:
            - image: circleci/node:13.12.0
        steps:
            - run:
                name: Add known hosts
                command: ssh-keyscan $SERVER_URL >> ~/.ssh/known_hosts
            - run: ssh -o StrictHostKeyChecking=no $SERVER 'cd corona && git pull && yarn install --production-false && yarn build && sudo yarn pm2 reload corona-service && exit'
workflows:
    version: 2
    build_and_lint:
        jobs:
            - setup
            - clean-lock
            - build:
                requires:
                    - setup
            - lint:
                requires:
                    - setup
                    - build
            - deploy:
                requires:
                    - setup
                    - clean-lock
                    - build
                    - lint
                filters:
                    branches:
                        only: master
