/** This is an autogenerated file, please do not change this file directly. */
declare namespace DeviceDetectorModuleScssModule {
    export interface IDeviceDetectorModuleScss {
        centerError: string;
    }
}

declare const DeviceDetectorModuleScssModule: DeviceDetectorModuleScssModule.IDeviceDetectorModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DeviceDetectorModuleScssModule.IDeviceDetectorModuleScss;
};

export = DeviceDetectorModuleScssModule;
