/** This is an autogenerated file, please do not change this file directly. */
declare namespace MainApplicationModuleScssModule {
    export interface IMainApplicationModuleScss {
        valueContainer: string;
    }
}

declare const MainApplicationModuleScssModule: MainApplicationModuleScssModule.IMainApplicationModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: MainApplicationModuleScssModule.IMainApplicationModuleScss;
};

export = MainApplicationModuleScssModule;
