/** This is an autogenerated file, please do not change this file directly. */
declare namespace BrowserModuleScssModule {
    export interface IBrowserModuleScss {
        basicInfoContainer: string;
        panelContainer: string;
    }
}

declare const BrowserModuleScssModule: BrowserModuleScssModule.IBrowserModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BrowserModuleScssModule.IBrowserModuleScss;
};

export = BrowserModuleScssModule;
