/** This is an autogenerated file, please do not change this file directly. */
declare namespace TabletOrMobileModuleScssModule {
    export interface ITabletOrMobileModuleScss {
        end: string;
        fadeIn: string;
        infoDialog: string;
        information: string;
        mapContainer: string;
        middle: string;
        start: string;
        statsContainer: string;
        tabletContainer: string;
    }
}

declare const TabletOrMobileModuleScssModule: TabletOrMobileModuleScssModule.ITabletOrMobileModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TabletOrMobileModuleScssModule.ITabletOrMobileModuleScss;
};

export = TabletOrMobileModuleScssModule;
