/** This is an autogenerated file, please do not change this file directly. */
declare namespace UsMapModuleScssModule {
    export interface IUsMapModuleScss {
        state: string;
        stateNoData: string;
    }
}

declare const UsMapModuleScssModule: UsMapModuleScssModule.IUsMapModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: UsMapModuleScssModule.IUsMapModuleScss;
};

export = UsMapModuleScssModule;
