/** This is an autogenerated file, please do not change this file directly. */
declare namespace VirusDataRendererModuleScssModule {
    export interface IVirusDataRendererModuleScss {
        valueContainer: string;
    }
}

declare const VirusDataRendererModuleScssModule: VirusDataRendererModuleScssModule.IVirusDataRendererModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: VirusDataRendererModuleScssModule.IVirusDataRendererModuleScss;
};

export = VirusDataRendererModuleScssModule;
