/** This is an autogenerated file, please do not change this file directly. */
declare namespace CurrentPathModuleScssModule {
    export interface ICurrentPathModuleScss {
        breadcrumb: string;
        breadcrumbBottomContainer: string;
        breadcrumbContainer: string;
        breadcrumbIcon: string;
        breadcrumbTopContainer: string;
        end: string;
        fadeIn: string;
        goToMyCounty: string;
        goToMyCountyMargin: string;
        middle: string;
        nationalBreadcrumbContainer: string;
        selectableBreadcrumb: string;
        start: string;
    }
}

declare const CurrentPathModuleScssModule: CurrentPathModuleScssModule.ICurrentPathModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CurrentPathModuleScssModule.ICurrentPathModuleScss;
};

export = CurrentPathModuleScssModule;
