/** This is an autogenerated file, please do not change this file directly. */
declare namespace HighlightedFipsInfoModuleScssModule {
    export interface IHighlightedFipsInfoModuleScss {
        connector: string;
        dateInfo: string;
        dateLabel: string;
        dateValue: string;
        end: string;
        hoverInfo: string;
        info: string;
        infoContainer: string;
        internalContainer: string;
        label: string;
        middle: string;
        start: string;
        title: string;
        transitioner: string;
        value: string;
    }
}

declare const HighlightedFipsInfoModuleScssModule: HighlightedFipsInfoModuleScssModule.IHighlightedFipsInfoModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: HighlightedFipsInfoModuleScssModule.IHighlightedFipsInfoModuleScss;
};

export = HighlightedFipsInfoModuleScssModule;
