/** This is an autogenerated file, please do not change this file directly. */
declare namespace LegendModuleScssModule {
    export interface ILegendModuleScss {
        end: string;
        legend: string;
        legendContainer: string;
        legendTicks: string;
        middle: string;
        start: string;
    }
}

declare const LegendModuleScssModule: LegendModuleScssModule.ILegendModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LegendModuleScssModule.ILegendModuleScss;
};

export = LegendModuleScssModule;
