/** This is an autogenerated file, please do not change this file directly. */
declare namespace MapColoringSelectionModuleScssModule {
    export interface IMapColoringSelectionModuleScss {
        active: string;
        end: string;
        fadeIn: string;
        mapColorContainer: string;
        middle: string;
        singleOption: string;
        start: string;
        title: string;
    }
}

declare const MapColoringSelectionModuleScssModule: MapColoringSelectionModuleScssModule.IMapColoringSelectionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: MapColoringSelectionModuleScssModule.IMapColoringSelectionModuleScss;
};

export = MapColoringSelectionModuleScssModule;
