/** This is an autogenerated file, please do not change this file directly. */
declare namespace MapHelpersModuleScssModule {
    export interface IMapHelpersModuleScss {
        mapHelpersContainer: string;
    }
}

declare const MapHelpersModuleScssModule: MapHelpersModuleScssModule.IMapHelpersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: MapHelpersModuleScssModule.IMapHelpersModuleScss;
};

export = MapHelpersModuleScssModule;
