/** This is an autogenerated file, please do not change this file directly. */
declare namespace BreakdownListModuleScssModule {
    export interface IBreakdownListModuleScss {
        breakdownListContainer: string;
        browser: string;
        caseBreakdownContainer: string;
        columnHeaders: string;
        end: string;
        fadeIn: string;
        filterContainer: string;
        isOpen: string;
        middle: string;
        singleBreakdown: string;
        start: string;
        totalCasesColumn: string;
    }
}

declare const BreakdownListModuleScssModule: BreakdownListModuleScssModule.IBreakdownListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BreakdownListModuleScssModule.IBreakdownListModuleScss;
};

export = BreakdownListModuleScssModule;
