/** This is an autogenerated file, please do not change this file directly. */
declare namespace ExplorationModuleScssModule {
    export interface IExplorationModuleScss {
        explorationContainer: string;
        growthCurveNonIdeal: string;
    }
}

declare const ExplorationModuleScssModule: ExplorationModuleScssModule.IExplorationModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ExplorationModuleScssModule.IExplorationModuleScss;
};

export = ExplorationModuleScssModule;
