/** This is an autogenerated file, please do not change this file directly. */
declare namespace PanelContainerModuleScssModule {
    export interface IPanelContainerModuleScss {
        end: string;
        fadeIn: string;
        middle: string;
        panelContainer: string;
        start: string;
        tabs: string;
    }
}

declare const PanelContainerModuleScssModule: PanelContainerModuleScssModule.IPanelContainerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PanelContainerModuleScssModule.IPanelContainerModuleScss;
};

export = PanelContainerModuleScssModule;
