/** This is an autogenerated file, please do not change this file directly. */
declare namespace ProjectionsModuleScssModule {
    export interface IProjectionsModuleScss {
        bottomText: string;
        date: string;
        description: string;
        descriptionIcon: string;
        end: string;
        fadeIn: string;
        green: string;
        icon: string;
        interventionsContainer: string;
        interventionsTitle: string;
        middle: string;
        mobile: string;
        nonIdealState: string;
        projectionContainer: string;
        projectionsDataContainer: string;
        red: string;
        singleInterventionContainer: string;
        singleProjectionContainer: string;
        spacingForDate: string;
        spinner: string;
        start: string;
        upperText: string;
    }
}

declare const ProjectionsModuleScssModule: ProjectionsModuleScssModule.IProjectionsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ProjectionsModuleScssModule.IProjectionsModuleScss;
};

export = ProjectionsModuleScssModule;
