/** This is an autogenerated file, please do not change this file directly. */
declare namespace StatsModuleScssModule {
    export interface IStatsModuleScss {
        divider: string;
        end: string;
        fadeIn: string;
        middle: string;
        start: string;
        statsContainer: string;
    }
}

declare const StatsModuleScssModule: StatsModuleScssModule.IStatsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StatsModuleScssModule.IStatsModuleScss;
};

export = StatsModuleScssModule;
